Book::HABTM_Authors.create!([
  {author_id: 3, book_id: 3},
  {author_id: 2, book_id: 1},
  {author_id: 1, book_id: 11},
  {author_id: 3, book_id: 2},
  {author_id: 3, book_id: 4},
  {author_id: 1, book_id: 12},
  {author_id: 3, book_id: 10},
  {author_id: 2, book_id: 9},
  {author_id: 1, book_id: 8},
  {author_id: 1, book_id: 7},
  {author_id: 2, book_id: 6},
  {author_id: 1, book_id: 5},
  {author_id: 1, book_id: 13},
  {author_id: 2, book_id: 15},
  {author_id: 2, book_id: 16}
])
Book::HABTM_Publishers.create!([
  {book_id: 4, publisher_id: 1},
  {book_id: 2, publisher_id: 1},
  {book_id: 3, publisher_id: 2},
  {book_id: 1, publisher_id: 2},
  {book_id: 5, publisher_id: 2},
  {book_id: 6, publisher_id: 2},
  {book_id: 7, publisher_id: 2},
  {book_id: 8, publisher_id: 2},
  {book_id: 9, publisher_id: 1},
  {book_id: 11, publisher_id: 1},
  {book_id: 10, publisher_id: 2},
  {book_id: 12, publisher_id: 2},
  {book_id: 13, publisher_id: 1},
  {book_id: 15, publisher_id: 1},
  {book_id: 16, publisher_id: 2}
])
Author::HABTM_Books.create!([
  {author_id: 3, book_id: 3},
  {author_id: 2, book_id: 1},
  {author_id: 1, book_id: 11},
  {author_id: 3, book_id: 2},
  {author_id: 3, book_id: 4},
  {author_id: 1, book_id: 12},
  {author_id: 3, book_id: 10},
  {author_id: 2, book_id: 9},
  {author_id: 1, book_id: 8},
  {author_id: 1, book_id: 7},
  {author_id: 2, book_id: 6},
  {author_id: 1, book_id: 5},
  {author_id: 1, book_id: 13},
  {author_id: 2, book_id: 15},
  {author_id: 2, book_id: 16}
])
Publisher::HABTM_Books.create!([
  {book_id: 4, publisher_id: 1},
  {book_id: 2, publisher_id: 1},
  {book_id: 3, publisher_id: 2},
  {book_id: 1, publisher_id: 2},
  {book_id: 5, publisher_id: 2},
  {book_id: 6, publisher_id: 2},
  {book_id: 7, publisher_id: 2},
  {book_id: 8, publisher_id: 2},
  {book_id: 9, publisher_id: 1},
  {book_id: 11, publisher_id: 1},
  {book_id: 10, publisher_id: 2},
  {book_id: 12, publisher_id: 2},
  {book_id: 13, publisher_id: 1},
  {book_id: 15, publisher_id: 1},
  {book_id: 16, publisher_id: 2}
])
Book.create!([
  {title: "Batman returnes", description: "A Photographic Atlas for the Biology Laboratory, Seventh Edition by Byron J. Adams and John L. Crawley is a full-color photographic atlas that provides a balanced visual representation of the diversity of biological organisms. It is designed to accompany any biology textbook or laboratory manual.", price: 100, year: 1991, isbn: "5-09-002630-0", image: "book1.jpg", pages: "456", language: "English", in_stock: false, old_price: nil},
  {title: "Legends of Cherkasy", description: "A Photographic Atlas for the Biology Laboratory, Seventh Edition by Byron J. Adams and John L. Crawley is a full-color photographic atlas that provides a balanced visual representation of the diversity of biological organisms. It is designed to accompany any biology textbook or laboratory manual.", price: 12, year: 2016, isbn: "5-09-002630-0", image: "book2.JPG", pages: "234", language: "English", in_stock: false, old_price: nil},
  {title: "Van De Graaff's Photographic Atlas for the Biology Laboratory", description: "A Photographic Atlas for the Biology Laboratory, Seventh Edition by Byron J. Adams and John L. Crawley is a full-color photographic atlas that provides a balanced visual representation of the diversity of biological organisms. It is designed to accompany any biology textbook or laboratory manual.", price: 158, year: 2009, isbn: "4-09-002630-0", image: "book3.jpg", pages: "234", language: "English", in_stock: true, old_price: nil},
  {title: "A Short History of Myth", description: "\u0093Human beings have always ben mythmakers.” So begins best-selling writer Karen Armstrong’s concise yet compelling investigation into myth: what it is, how it has evolved, and why we still so desperately need it. She takes us from the Paleolithic period and the myths of the hunters right up to the \u0093Great Western Transformation” of the last five hundred years and the discrediting of myth by science. The history of myth is the history of humanity, our stories and beliefs, our curiosity and attempts to understand the world, which link us to our ancestors and each other. Heralding a major series of retellings of international myths by authors from around the world, Armstrong’s characteristically insightful and eloquent book serves as a brilliant and thought-provoking introduction to myth in the broadest sense\u0097and explains why if we dismiss it, we do so at our peril.", price: 199, year: 2000, isbn: "5-09-002630-0", image: "book4.JPG", pages: "123", language: "English", in_stock: true, old_price: 399},
  {title: "Automotive Handbook 9E by Bosch GmbH Robert Hardcover Book (English)", description: "\"The Automotive Handbook, 9th Edition,\" is the flagship publication in the Bosch handbook series on automotive technologies and is one of the most definitive sets of reference books that automotive engineers have at their disposal.As progress in the field of automotive engineering has grown apace it has expanded from 96 pages in 1936, to 1544 pages today. This new edition is significantly updated, with key changes including coverage of electrical systems and batteries for hybrid drives. Many other new chapters are also included, which cover emergency braking systems, active pedestrian protection and the future of driver assistance.\"The Automotive Handbook, 9th Edition\" is a quick and easy reference guide for engineers in industry and also for students in automotive engineering.", price: 16, year: 1991, isbn: "1119032946", image: "book5.jpg", pages: "123", language: "English", in_stock: true, old_price: nil},
  {title: "Lymphedema and Lipedema Nutrition Guide", description: "\"The Automotive Handbook, 9th Edition,\" is the flagship publication in the Bosch handbook series on automotive technologies and is one of the most definitive sets of reference books that automotive engineers have at their disposal.As progress in the field of automotive engineering has grown apace it has expanded from 96 pages in 1936, to 1544 pages today. This new edition is significantly updated, with key changes including coverage of electrical systems and batteries for hybrid drives. Many other new chapters are also included, which cover emergency braking systems, active pedestrian protection and the future of driver assistance.\"The Automotive Handbook, 9th Edition\" is a quick and easy reference guide for engineers in industry and also for students in automotive engineering.", price: 35, year: 1991, isbn: "1119032946", image: "book7.JPG", pages: "123", language: "English", in_stock: true, old_price: nil},
  {title: "The Anime Art of Hayao Miyazaki by Dani Cavallaro ", description: "\"The Automotive Handbook, 9th Edition,\" is the flagship publication in the Bosch handbook series on automotive technologies and is one of the most definitive sets of reference books that automotive engineers have at their disposal.As progress in the field of automotive engineering has grown apace it has expanded from 96 pages in 1936, to 1544 pages today. This new edition is significantly updated, with key changes including coverage of electrical systems and batteries for hybrid drives. Many other new chapters are also included, which cover emergency braking systems, active pedestrian protection and the future of driver assistance.\"The Automotive Handbook, 9th Edition\" is a quick and easy reference guide for engineers in industry and also for students in automotive engineering.", price: 16, year: 1991, isbn: "1119032946", image: "book8.JPG", pages: "123", language: "English", in_stock: true, old_price: nil},
  {title: "The Age of Absurdity", description: "\"The Automotive Handbook, 9th Edition,\" is the flagship publication in the Bosch handbook series on automotive technologies and is one of the most definitive sets of reference books that automotive engineers have at their disposal.As progress in the field of automotive engineering has grown apace it has expanded from 96 pages in 1936, to 1544 pages today. This new edition is significantly updated, with key changes including coverage of electrical systems and batteries for hybrid drives. Many other new chapters are also included, which cover emergency braking systems, active pedestrian protection and the future of driver assistance.\"The Automotive Handbook, 9th Edition\" is a quick and easy reference guide for engineers in industry and also for students in automotive engineering.", price: 16, year: 1991, isbn: "1119032946", image: "book9.JPG.jpg", pages: "123", language: "English", in_stock: true, old_price: nil},
  {title: "The Unofficial LEGO Builder's Guide", description: "What's the difference between a tile and a plate? Why isn't it a good idea to stack bricks in columns to make a wall? How do you build a LEGO mosaic or build at different scales? You'll find the answers to these and other questions in The Unofficial LEGO Builder's Guide. Now in full color, this brand-new edition of a well-loved favorite will show you how to: Construct models that won't fall apart Choose the right pieces and substitute when needed Build to micro, jumbo, and miniland scale Make playable board games out of LEGO pieces Create photo mosaics and curved sculptures Build a miniature space shuttle, a minifig-sized train station, and more Of course, the real fun of LEGO building lies in creating your own modelsfrom choosing the subject to clicking that final brick into place. Learn how in The Unofficial LEGO Builder's Guide. Includes the Brickopedia, a visual dictionary of nearly 300 of the most commonly used LEGO elements!", price: 26, year: 2001, isbn: "1593274416", image: "book10.JPG", pages: "200", language: "English", in_stock: false, old_price: nil},
  {title: "Details about  The Art of Communicating", description: "What's the difference between a tile and a plate? Why isn't it a good idea to stack bricks in columns to make a wall? How do you build a LEGO mosaic or build at different scales? You'll find the answers to these and other questions in The Unofficial LEGO Builder's Guide. Now in full color, this brand-new edition of a well-loved favorite will show you how to: Construct models that won't fall apart Choose the right pieces and substitute when needed Build to micro, jumbo, and miniland scale Make playable board games out of LEGO pieces Create photo mosaics and curved sculptures Build a miniature space shuttle, a minifig-sized train station, and more Of course, the real fun of LEGO building lies in creating your own modelsfrom choosing the subject to clicking that final brick into place. Learn how in The Unofficial LEGO Builder's Guide. Includes the Brickopedia, a visual dictionary of nearly 300 of the most commonly used LEGO elements!", price: 26, year: 2001, isbn: "1593274416", image: "book11.jpg", pages: "200", language: "English", in_stock: true, old_price: nil},
  {title: "Biology Essentials for Dummies", description: "What's the difference between a tile and a plate? Why isn't it a good idea to stack bricks in columns to make a wall? How do you build a LEGO mosaic or build at different scales? You'll find the answers to these and other questions in The Unofficial LEGO Builder's Guide. Now in full color, this brand-new edition of a well-loved favorite will show you how to: Construct models that won't fall apart Choose the right pieces and substitute when needed Build to micro, jumbo, and miniland scale Make playable board games out of LEGO pieces Create photo mosaics and curved sculptures Build a miniature space shuttle, a minifig-sized train station, and more Of course, the real fun of LEGO building lies in creating your own modelsfrom choosing the subject to clicking that final brick into place. Learn how in The Unofficial LEGO Builder's Guide. Includes the Brickopedia, a visual dictionary of nearly 300 of the most commonly used LEGO elements!", price: 26, year: 2001, isbn: "1593274416", image: "book12.jpg", pages: "200", language: "English", in_stock: true, old_price: 46},
  {title: "The Unofficial LEGO Builder's Guide", description: "What's the difference between a tile and a plate? Why isn't it a good idea to stack bricks in columns to make a wall? How do you build a LEGO mosaic or build at different scales? You'll find the answers to these and other questions in The Unofficial LEGO Builder's Guide. Now in full color, this brand-new edition of a well-loved favorite will show you how to: Construct models that won't fall apart Choose the right pieces and substitute when needed Build to micro, jumbo, and miniland scale Make playable board games out of LEGO pieces Create photo mosaics and curved sculptures Build a miniature space shuttle, a minifig-sized train station, and more Of course, the real fun of LEGO building lies in creating your own modelsfrom choosing the subject to clicking that final brick into place. Learn how in The Unofficial LEGO Builder's Guide. Includes the Brickopedia, a visual dictionary of nearly 300 of the most commonly used LEGO elements!", price: 19, year: 2005, isbn: "1593274416", image: "book13.jpg", pages: "200", language: "English", in_stock: true, old_price: nil},
  {title: "The Anime Art of Hayao Miyazak", description: "The Automotive Handbook, 9th Edition,\" is the flagship publication in the Bosch handbook series on automotive technologies and is one of the most definitive sets of reference books that automotive engineers have at their disposal.As progress in the field of automotive engineering has grown apace it has expanded from 96 pages in 1936, to 1544 pages today. This new edition is significantly updated, with key changes including coverage of electrical systems and batteries for hybrid drives. Many other new chapters are also included, which cover emergency braking systems, active pedestrian protection and the future of driver assistance.\"The Automotive Handbook, 9th Edition\" is a quick and easy reference guide for engineers in industry and also for students in automotive engineering.", price: 45, year: 1678, isbn: "1119032946", image: "book14.jpg", pages: "345", language: "English", in_stock: true, old_price: 67},
  {title: "The benefits of CETA", description: "The EU recently concluded a new free trade deal with Canada - the Comprehensive Economic and Trade Agreement, or CETA for short. The deal will bring benefits for people and businesses across Europe. It will help to generate growth and jobs by: boosting exports, lowering the cost of the inputs businesses need to make their products, offering greater choice for consumers, and upholding the EU's strict standards for products. This booklet summarises how", price: 123, year: 2005, isbn: "978-92-79-59055-9", image: "book15.jpg", pages: "234", language: "English", in_stock: false, old_price: 134},
  {title: "Breaking the Mould", description: "Sport is integral to Australian life and identity, and we’re rightly proud of our sporting achievements. But less glorious is the fact that, when it comes to the games we play, half of the population doesn’t get a look-in. According to the latest statistics, 81 per cent of sports media covers male-only sport, while just 8.7 per cent focuses on women. That’s right – horses got more attention than female athletes! Pick any sport and it’s easy to find examples of stark gender inequality and double standards so glaring that they’re almost laughable.", price: 34, year: 2345, isbn: "1119032946", image: "book16.jpg", pages: "123", language: "English", in_stock: false, old_price: 35}
])
Author.create!([
  {first_name: "Adams", last_name: "Crawley"},
  {first_name: "Bryon", last_name: "Jackson"},
  {first_name: "John", last_name: "Luise"}
])
BookCategory.create!([
  {book_id: 1, category_id: 1},
  {book_id: 3, category_id: 2},
  {book_id: 2, category_id: 2},
  {book_id: 8, category_id: 1},
  {book_id: 5, category_id: 3},
  {book_id: nil, category_id: 2},
  {book_id: nil, category_id: 2},
  {book_id: 6, category_id: 2},
  {book_id: nil, category_id: 3},
  {book_id: 4, category_id: 3},
  {book_id: nil, category_id: 1},
  {book_id: 7, category_id: 1},
  {book_id: 9, category_id: 1},
  {book_id: nil, category_id: 1},
  {book_id: nil, category_id: 1},
  {book_id: nil, category_id: 1},
  {book_id: nil, category_id: 2},
  {book_id: nil, category_id: 2},
  {book_id: 10, category_id: 2},
  {book_id: 11, category_id: 2},
  {book_id: 12, category_id: 3},
  {book_id: 13, category_id: 3},
  {book_id: 14, category_id: 1},
  {book_id: 15, category_id: 1},
  {book_id: 16, category_id: 2}
])
Category.create!([
  {name: "Poetry", position: 1},
  {name: "Horror", position: 2},
  {name: "Science", position: 3}
])
Order.create!([
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "1998.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava v", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "mikle", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "mikle v", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "158.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "mikle s", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "158.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "1998.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "mikle1", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "999.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "3155.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "sasha1", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "16.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "", customer_last_name: "", customer_phone_number: "", customer_email: "booksssstore@gmail.com", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "398.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "Mikle", customer_last_name: "Jordan", customer_phone_number: "1234", customer_email: "booksssstore@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "booksssstore@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "398.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "booksssstore@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "215.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "573.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "398.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "398.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "215.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "0.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "", customer_last_name: "", customer_phone_number: "", customer_email: "", customer_house: "", customer_city: "", customer_postal_code: ""},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "mikle@gmail.com", customer_house: "qwer1", customer_city: "qwer", customer_postal_code: "1234"},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: nil, customer_last_name: nil, customer_phone_number: nil, customer_email: nil, customer_house: nil, customer_city: nil, customer_postal_code: nil},
  {subtotal: "199.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "1", customer_last_name: "2", customer_phone_number: "1234", customer_email: "booksssstore@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"},
  {subtotal: "26.0", tax: nil, shipping: nil, total: nil, order_status_id: 1, customer_first_name: "slava", customer_last_name: "vaka", customer_phone_number: "1234", customer_email: "booksssstore@gmail.com", customer_house: "qwer12", customer_city: "qwer", customer_postal_code: "18029"}
])
OrderBook.create!([
  {book_id: 3, order_id: 1, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 11, unit_price: "999.0", quantity: 2, total_price: "1998.0"},
  {book_id: 3, order_id: 13, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 15, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 16, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 17, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 18, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 19, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 20, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 21, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 22, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 23, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 23, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 23, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 23, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 25, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 26, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 27, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 28, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 29, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 30, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 31, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 32, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 33, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 35, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 37, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 39, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 40, unit_price: "999.0", quantity: 3, total_price: "2997.0"},
  {book_id: 3, order_id: 42, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 44, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 46, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 48, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 49, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 50, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 50, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 51, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 51, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 52, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 53, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 54, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 55, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 56, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 57, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: nil, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: nil, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: nil, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 58, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 59, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 60, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 61, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 3, order_id: 62, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 63, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 64, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 64, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 65, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 66, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 67, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 68, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 69, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 70, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 71, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 72, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 73, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 73, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 74, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 75, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 3, order_id: 75, unit_price: "158.0", quantity: 1, total_price: "158.0"},
  {book_id: 4, order_id: 75, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 4, order_id: 75, unit_price: "999.0", quantity: 1, total_price: "999.0"},
  {book_id: 5, order_id: 76, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 4, order_id: 77, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 77, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 78, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 79, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 80, unit_price: "199.0", quantity: 2, total_price: "398.0"},
  {book_id: 4, order_id: 81, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 82, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 5, order_id: 82, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 3, order_id: 83, unit_price: "158.0", quantity: 2, total_price: "316.0"},
  {book_id: 7, order_id: 83, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 10, order_id: 83, unit_price: "26.0", quantity: 1, total_price: "26.0"},
  {book_id: 5, order_id: 83, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 4, order_id: 83, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 84, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 84, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 85, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 85, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 5, order_id: 86, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 4, order_id: 86, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 5, order_id: 87, unit_price: "16.0", quantity: 1, total_price: "16.0"},
  {book_id: 4, order_id: 89, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 90, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 4, order_id: 91, unit_price: "199.0", quantity: 1, total_price: "199.0"},
  {book_id: 11, order_id: 92, unit_price: "26.0", quantity: 1, total_price: "26.0"}
])
OrderStatus.create!([
  {name: "In Progress"},
  {name: "Confirmed"},
  {name: "Complited"},
  {name: "Shipped"},
  {name: "Cancelled"}
])
Publisher.create!([
  {publisher_name: "Canongate U.S."},
  {publisher_name: "SELECTION DAY"},
  {publisher_name: "Pan Macmillan Australia "}
])
Review.create!([
  {rating: 3, comment: "Human beings have always been mythmakers.", user_id: 2, book_id: 4, review_status_id: 2},
  {rating: 2, comment: "Human beings have always been ", user_id: 2, book_id: 4, review_status_id: 2},
  {rating: 2, comment: "Contact info", user_id: 2, book_id: 4, review_status_id: 2},
  {rating: 5, comment: "\u0093Human beings have always been mythmakers", user_id: 2, book_id: 4, review_status_id: 2},
  {rating: 3, comment: "\u0093Human beings have always been", user_id: 2, book_id: 4, review_status_id: 2},
  {rating: 4, comment: "Thank you!", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "good", user_id: 2, book_id: 4, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 4, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 4, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 4, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 4, review_status_id: 1},
  {rating: 5, comment: "nice", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 4, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 5, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 3, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 1, comment: "", user_id: 2, book_id: 5, review_status_id: 1},
  {rating: 2, comment: "", user_id: 2, book_id: 5, review_status_id: 1}
])
ReviewStatus.create!([
  {status: "Draft"},
  {status: "Approved"}
])
User.create!([
  {first_name: "Slava", last_name: "Vakarchuck", email: "slava@gmail.com", password_digest: "$2a$10$VXNK/YKTxkZNBOjwgAOHxufyCAcUarK.iZXojEkk.RG5tn316nunS"},
  {first_name: "Mikle", last_name: "Jordan", email: "mikle@gmail.com", password_digest: "$2a$10$nH1LUENl/S./nMTXemJtXuWAFXl26w/CsvIKq65/XqXh3TJouXfaC"},
  {first_name: "Denis", last_name: "Rodman", email: "denis@gmail.com", password_digest: "$2a$10$2ZNJTXCbsoUJli.JLvGmzuY65t0jU/HX7QQaMK3KvQQ/QGjhMIfYe"},
  {first_name: "Sasha", last_name: "Best", email: "sasha@gmail.com", password_digest: "$2a$10$LbSsYCrpx/oQHceCdDZESOG3alSnasshoHQMyWK8WwrDTJlEKM//S"}
])
